import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Generates a premium PDF for the research report.
 * Captures the full content of the report viewer.
 */
export const exportReportPDF = async (task) => {
    if (!task || !task.report) {
        console.error("No report data available for PDF export");
        return;
    }

    // Create a temporary container for PDF rendering
    const element = document.createElement('div');
    element.className = 'pdf-export-container';
    element.style.padding = '40px';
    element.style.background = '#0F172A'; // Match app background
    element.style.color = '#F8FAFC';
    element.style.fontFamily = 'Inter, system-ui, sans-serif';
    element.style.width = '800px';
    element.style.position = 'absolute';
    element.style.left = '-10000px';

    const report = task.report;
    const critique = task.critique;

    // Header logic
    element.innerHTML = `
        <div style="border-bottom: 2px solid #1E293B; padding-bottom: 20px; margin-bottom: 30px;">
            <h1 style="color: #22D3EE; margin: 0; font-size: 28px;">Research Report</h1>
            <p style="color: #94A3B8; margin: 5px 0 0 0;">Topic: ${task.topic || 'General Research'}</p>
            <p style="color: #64748B; margin: 5px 0 0 0; font-size: 12px;">Date: ${new Date().toLocaleDateString()}</p>
        </div>

        <div style="margin-bottom: 30px;">
            <h2 style="color: #A855F7; font-size: 20px; border-left: 4px solid #A855F7; padding-left: 10px;">Executive Summary</h2>
            <div style="line-height: 1.6; color: #E2E8F0;">${report.summary || 'No summary provided.'}</div>
        </div>

        <div id="pdf-sections">
            ${(report.sections || []).map(section => `
                <div style="margin-bottom: 25px; page-break-inside: avoid;">
                    <h3 style="color: #22D3EE; font-size: 18px; margin-bottom: 10px;">${section.title}</h3>
                    <div style="line-height: 1.6; color: #CBD5E1;">${section.content}</div>
                </div>
            `).join('')}
        </div>

        ${report.sources && report.sources.length > 0 ? `
            <div style="margin-top: 40px; border-top: 1px solid #1E293B; padding-top: 20px;">
                <h3 style="color: #94A3B8; font-size: 16px;">Sources & References</h3>
                <ul style="color: #64748B; font-size: 13px;">
                    ${report.sources.map(s => `<li>${s.url || s}</li>`).join('')}
                </ul>
            </div>
        ` : ''}

        ${critique ? `
            <div style="margin-top: 50px; padding: 20px; border: 1px dashed #334155; border-radius: 8px; background: rgba(30, 41, 59, 0.5);">
                <h2 style="color: #10B981; font-size: 18px; margin-top: 0;">AI Quality Review</h2>
                <div style="font-size: 14px; line-height: 1.5; color: #94A3B8;">
                    <strong>Quality Score: ${critique.score || 'N/A'}/10</strong><br/>
                    ${typeof critique === 'string' ? critique : (critique.text || critique.critique || '')}
                </div>
            </div>
        ` : ''}

        <div style="text-align: center; margin-top: 50px; color: #475569; font-size: 10px; border-top: 1px solid #1E293B; padding-top: 10px;">
            Generated by AI Research Workspace Tool
        </div>
    `;

    document.body.appendChild(element);

    try {
        const canvas = await html2canvas(element, {
            scale: 2,
            useCORS: true,
            backgroundColor: '#0F172A',
            logging: false
        });

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: 'a4'
        });

        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
        pdf.save(`Research_Report_${task.topic.replace(/\s+/g, '_')}.pdf`);
    } catch (err) {
        console.error("PDF generation failed:", err);
    } finally {
        document.body.removeChild(element);
    }
};
